# Generated by Django 4.2.8 on 2024-01-10 05:17

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collegesettings",
            options={"verbose_name_plural": "College Settings"},
        ),
        migrations.AlterModelOptions(
            name="semestersettings",
            options={"verbose_name_plural": "Semester Settings"},
        ),
        migrations.RenameField(
            model_name="semestersettings",
            old_name="end_date",
            new_name="end_month_day",
        ),
        migrations.RenameField(
            model_name="semestersettings",
            old_name="start_date",
            new_name="start_month_day",
        ),
        migrations.AddField(
            model_name="collegesettings",
            name="_singleton",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="This field is used to ensure that only one instance of this model exists.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="semestersettings",
            name="semester",
            field=core.fields.SemesterField(unique=True),
        ),
        migrations.AddConstraint(
            model_name="collegesettings",
            constraint=models.CheckConstraint(
                check=models.Q(("_singleton", True)), name="college_settings_singleton"
            ),
        ),
    ]
