# Generated by Django 4.2.8 on 2024-01-04 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The start date for the validity of this fee."
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        help_text="The end date for the validity of this fee."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentPenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_paid", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Student Penalties",
            },
        ),
        migrations.CreateModel(
            name="StudentPenaltyPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "CASH"),
                            ("CHALLAN", "CHALLAN"),
                            ("UPI", "UPI"),
                            ("ONLINE", "ONLINE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "txn_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID for electronic payments.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for challan payments.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "penalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.studentpenalty",
                    ),
                ),
            ],
        ),
    ]
