# Generated by Django 4.2.8 on 2024-01-03 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0002_course_code_department_code_stream_code"),
        ("student", "0003_alter_student_admission_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valid_from",
                    models.DateField(
                        help_text="The start date for the validity of this fee."
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        help_text="The end date for the validity of this fee."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentPenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_mode", models.CharField(max_length=20)),
                ("paid_date", models.DateField()),
                ("txn_id", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Penalties",
                "indexes": [
                    models.Index(
                        fields=["student", "is_paid"], name="student_penalty_idx"
                    )
                ],
            },
        ),
    ]
