# Generated by Django 4.2.8 on 2024-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpenalty",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Reference number for challan payments.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpenalty",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "CASH"),
                    ("CHALLAN", "CHALLAN"),
                    ("UPI", "UPI"),
                    ("ONLINE", "ONLINE"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentpenalty",
            name="txn_id",
            field=models.CharField(
                blank=True,
                help_text="Transaction ID for electronic payments.",
                max_length=255,
                null=True,
            ),
        ),
    ]
