# Generated by Django 4.2.8 on 2024-01-03 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_studentpenalty_reference_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpenalty",
            name="paid_date",
        ),
        migrations.RemoveField(
            model_name="studentpenalty",
            name="payment_mode",
        ),
        migrations.RemoveField(
            model_name="studentpenalty",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="studentpenalty",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="studentpenalty",
            name="txn_id",
        ),
        migrations.CreateModel(
            name="StudentPenaltyPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "CASH"),
                            ("CHALLAN", "CHALLAN"),
                            ("UPI", "UPI"),
                            ("ONLINE", "ONLINE"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "txn_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID for electronic payments.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number for challan payments.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "penalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.studentpenalty",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["payment_mode"], name="penalty_pay_mode_idx")
                ],
            },
        ),
    ]
