# Generated by Django 4.2.8 on 2024-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0003_alter_tutor_course_alter_tutor_stream"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
