# Generated by Django 4.2.8 on 2024-01-15 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("block", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "residency_category",
                    models.CharField(
                        choices=[("Mens", "MENS"), ("Womens", "WOMENS")], max_length=10
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum number of persons that can be accomodated"
                    ),
                ),
                (
                    "current_occupancy",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of persons currently accomodated"
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hosteller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room", models.CharField(blank=True, max_length=10, null=True)),
                ("joining_date", models.DateField()),
                ("vacated_date", models.DateField(blank=True, null=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostellers",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosteller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="hosteller",
            constraint=models.UniqueConstraint(
                fields=("hostel", "user"), name="unique_hosteller"
            ),
        ),
    ]
