# Generated by Django 4.2.8 on 2024-01-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="residency_category",
            field=models.CharField(
                choices=[("mens", "MENS"), ("womens", "WOMENS")], max_length=10
            ),
        ),
    ]
