# Generated by Django 4.2.8 on 2024-01-04 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="intake",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of students that can be admitted to this course per batch",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="auto_promotion",
            field=models.BooleanField(
                default=False,
                help_text="If checked, students will be automatically promoted to next semester",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.CharField(
                help_text="Duration of the course (e.g. 6 semesters)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CourseSyllabus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attachment", models.FileField(upload_to="course/syllabus/")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
