# Generated by Django 4.2.8 on 2024-01-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Course code (e.g. CS101)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Department code (e.g. CS)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Stream code (e.g. CS101)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
    ]
