# Generated by Django 4.2.8 on 2024-01-09 04:54

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_course_intake_alter_course_auto_promotion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("semester", core.fields.SemesterField()),
                ("credit", models.PositiveIntegerField(blank=True, null=True)),
                ("is_elective", models.BooleanField(default=False)),
                ("is_lab", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.course",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.stream",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
