from .base import CustomError  # noqa
from .college_settings_exists import CollegeSettingsAlreadyExists  # noqa
from .date_order_violation import DateOrderViolationError  # noqa
from .duplicate_attendance import DuplicateAttendanceEntry  # noqa
from .duplicate_exam import DuplicateExamEntry  # noqa
from .duplicate_exam_result import DuplicateExamResultEntry  # noqa
from .duplicate_exam_type import DuplicateExamTypeEntry  # noqa
from .duplicate_timetable import DuplicateAlternateTimeTableEntry  # noqa
from .duplicate_timetable import DuplicateTimeTableEntry  # noqa
from .leave_request_update_denied import LeaveRequestUpdateDeniedError  # noqa
from .payment_field_required import PaymentFieldRequired  # noqa
from .time_order_violation import TimeOrderViolationError  # noqa
