# Generated by Django 4.2.8 on 2024-01-02 06:54

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.enums
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academic", "0002_course_code_department_code_stream_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("admission_num", models.CharField(max_length=100)),
                ("batch", core.fields.BatchYearField()),
                ("birthday", models.DateField()),
                ("enrolled_date", models.DateField()),
                (
                    "course_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "ENROLLED"),
                            ("completed", "COMPLETED"),
                            ("discontinued", "DISCONTINUED"),
                            ("dismissed", "DIMISSED"),
                        ],
                        default=student.enums.CourseStatus["ENROLLED"],
                        max_length=50,
                    ),
                ),
                ("course_completion_date", models.DateField(blank=True, null=True)),
                ("discontinued_date", models.DateField(blank=True, null=True)),
                ("dismissed_date", models.DateField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.department",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.stream",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["batch"], name="batch_idx")],
            },
        ),
    ]
