# Generated by Django 4.2.8 on 2024-01-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_num",
            field=models.PositiveBigIntegerField(),
        ),
    ]
