# Generated by Django 4.2.8 on 2024-01-11 05:03

from django.db import migrations, models
import django.db.models.deletion
import student.enums
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("faculty", "0002_initial"),
        ("student", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("approved", "APPROVED"),
                            ("rejected", "REJECTED"),
                        ],
                        default=student.enums.LeaveRequestStatus["PENDING"],
                        max_length=15,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="faculty.tutor"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["student"], name="student_idx")],
            },
        ),
    ]
