# Generated by Django 4.2.8 on 2024-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_admission_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_num",
            field=models.PositiveBigIntegerField(editable=False, unique=True),
        ),
    ]
