# Generated by Django 4.2.8 on 2024-01-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "MALE"), ("female", "FEMALE")],
                default="male",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
