# Generated by Django 4.2.8 on 2024-01-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_college_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user is a college admin.",
            ),
        ),
    ]
