# Generated by Django 4.2.8 on 2024-01-09 05:04

import core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialTimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "MONDAY"),
                            ("tuesday", "TUESDAY"),
                            ("wednesday", "WEDNESDAY"),
                            ("thursday", "THURSDAY"),
                            ("friday", "FRIDAY"),
                            ("saturday", "SATURDAY"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="alternatetimetable",
            name="batch",
            field=core.fields.BatchYearField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alternatetimetable",
            name="semester",
            field=core.fields.SemesterField(default=1),
            preserve_default=False,
        ),
    ]
