# Generated by Django 4.2.8 on 2024-01-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_specialtimeslot_alternatetimetable_batch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialtimeslot",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="specialtimeslot",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="specialtimeslot",
            name="id",
        ),
        migrations.RemoveField(
            model_name="specialtimeslot",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="specialtimeslot",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="specialtimeslot",
            name="timeslot_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="attendance.timeslot",
            ),
            preserve_default=False,
        ),
    ]
