# Generated by Django 4.2.8 on 2024-02-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_remove_timetable_unique_timetable_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["batch", "semester"], name="batch_semester_index"
            ),
        ),
    ]
