# Generated by Django 4.2.8 on 2024-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_timetable_batch_semester_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alternatetimetable",
            index=models.Index(
                fields=["batch", "semester"], name="alt_tt_batch_semester_idx"
            ),
        ),
    ]
