# Generated by Django 4.2.8 on 2024-02-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_alternatetimetable_alt_tt_batch_semester_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["batch", "semester"], name="attendance_batch_semester_idx"
            ),
        ),
    ]
