# Generated by Django 4.2.8 on 2024-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_attendance_attendance_batch_semester_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_attendance",
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("time_slot", "student", "date", "semester", "batch"),
                name="unique_attendance",
            ),
        ),
    ]
